### ISSUE TITLE
Search bar text

### ISSUE THREAD

**Issue by northcoders-chris** [lc3t35/meteor-datatables-bootstrap3#1]
Hi mate. I was wondering why the bootstrap three version does not display "search" next to the search input? I usually does with jQuery dataTables. 

Cheers, thanks for the package!

**Comment by lc3t35** [comment]
@northcoder, it should ! (it's on the right side with bootstrap), I have a search input at the right side on tests.
Can you try the last update ?

**Comment by lc3t35** [comment]
If you need reopen the issue ;)
