### ISSUE TITLE
Datatables Issues with Joining of Collections (publish composite) - Meteor JS

### ISSUE THREAD

**Issue by manusharma1** [lc3t35/meteor-datatables-bootstrap3#2]
Hi,

I am using loftsteinn:datatables-bootstrap3 (https://github.com/oskarszoon/meteor-datatables-bootstrap3/) which is forked from your code. I am trying to display the data using joining of two collections, for Joining of collections I am using : https://atmospherejs.com/reywood/publish-composite.

The Issue : as the data gets fetched and the page gets rendered with the table it shows 0 records, but after a few seconds rows get populated and datatable gets filled but still shows 0 records.

To Counter this issue I have to set timeout for few seconds and then it shows correctly.

Is there any better way, as I feel that in case the data gets increased, I may face issues again.

Thanks and Best Regards,
Manu

**Comment by lc3t35** [comment]
Thank you, i've seen that datatables is 1.10.10 now, so I will update my package.
I will try make a little test to cover this issue.

**Comment by lc3t35** [comment]
I think it is the way you trigger the rendering that generate this issue, it's not related to this package.
You might wait that data is available (i.e. not zero), before updating the collection ?

**Comment by manusharma1** [comment]
Hi Laurent,

Thanks for your reply, Right now I am actually using the timeout to get this issue solved, The other way around which I am also discussing on Stackoverflow @ http://stackoverflow.com/questions/34219406/datatables-with-meteor-using-collections-join/

**Comment by lc3t35** [comment]
Solution without timeout is here : http://stackoverflow.com/a/34500970/1054045

**Comment by manusharma1** [comment]
Hi Laurent, 

Thanks for an update, I will check this and will get back if this solution works for me. 

Thanks and Best Regards,
Manu
